# Generated by Django 4.0.2 on 2022-02-07 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='USER_TYPES',
            field=models.SmallIntegerField(choices=[(1, 'Super Admin'), (2, 'Admin'), (3, 'User')], default=1, verbose_name='User type'),
        ),
    ]
