# Generated by Django 4.0.2 on 2022-02-07 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_user_types'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='USER_TYPES',
            new_name='user_type',
        ),
    ]
