# Generated by Django 4.0.2 on 2022-02-08 13:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
        ('accounts', '0004_profile_address_profile_img_profile_mobile_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profile',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='general.department'),
        ),
        migrations.AddField(
            model_name='profile',
            name='employee_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Employee ID'),
        ),
        migrations.AddField(
            model_name='profile',
            name='job_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Job Title'),
        ),
        migrations.AddField(
            model_name='profile',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='general.property'),
        ),
    ]
