# Generated by Django 4.0.2 on 2022-02-08 13:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Update date')),
                ('state', models.SmallIntegerField(choices=[(-1, 'Deleted'), (0, 'Paused'), (1, 'Active'), (2, 'For Review'), (3, 'Expired'), (4, 'Cancelled')], default=1, verbose_name='Publish state')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(app_label)s_%(class)s_modified_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='general.base')),
                ('location', models.CharField(max_length=255, verbose_name='Location Name')),
            ],
            bases=('general.base',),
        ),
        migrations.CreateModel(
            name='ResourceSubType',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='general.base')),
                ('resource_sub_type_name', models.CharField(max_length=255, verbose_name='Resource Sub Type Name')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('general.base',),
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='general.base')),
                ('resource_name', models.CharField(max_length=255, verbose_name='Resource Name')),
                ('resource_sub_type', models.ManyToManyField(blank=True, null=True, to='general.ResourceSubType')),
            ],
            bases=('general.base',),
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='general.base')),
                ('name', models.CharField(max_length=255, verbose_name='Department Name')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('general.base',),
        ),
    ]
