# Generated by Django 4.0.2 on 2022-02-11 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resourcesubtype',
            name='profile',
        ),
    ]
