# Generated by Django 4.0.2 on 2022-02-11 18:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('general', '0002_remove_resourcesubtype_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requester',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='general.base')),
                ('temporary_user', models.BooleanField(default=True, verbose_name='Temporary User')),
                ('deactivation_date', models.DateTimeField(verbose_name='Creation date')),
                ('additional_comment', models.CharField(blank=True, max_length=1000, null=True)),
                ('resource_sub_type', models.ManyToManyField(blank=True, null=True, to='general.ResourceSubType')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('general.base',),
        ),
    ]
