# Generated by Django 4.0.2 on 2022-02-12 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0003_requester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requester',
            name='deactivation_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Creation date'),
        ),
    ]
