# Generated by Django 4.0.2 on 2022-02-14 13:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('general', '0005_adminrequesterapprovalhirearchy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='general.base')),
                ('subject', models.CharField(blank=True, max_length=500, null=True)),
                ('source_type', models.SmallIntegerField(choices=[(1, 'Phone'), (2, 'Whatsapp'), (3, 'FB'), (4, 'Other')], default=1, verbose_name='User type')),
                ('status_type', models.SmallIntegerField(choices=[(1, 'Open'), (2, 'Pending'), (3, 'Resolved'), (4, 'Closed')], default=1, verbose_name='User type')),
                ('urgency_type', models.SmallIntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High')], default=1, verbose_name='User type')),
                ('priority_type', models.SmallIntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High'), (3, 'Urgent')], default=1, verbose_name='User type')),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('general.base',),
        ),
    ]
