# Generated by Django 4.0.2 on 2022-02-14 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tickets',
            old_name='user',
            new_name='agent',
        ),
    ]
