# Generated by Django 4.0.2 on 2022-02-15 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_rename_user_tickets_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='ticket_state',
            field=models.SmallIntegerField(choices=[(1, 'Tickets on Hold'), (2, 'Unassigned Tickets'), (3, 'Ticket IM Wathing'), (4, 'Overdue Tickets'), (5, 'Open Tickets'), (6, 'Ticket Due Today')], default=1, verbose_name='Publish state'),
        ),
    ]
