# Generated by Django 4.0.2 on 2022-02-16 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_tickets_ticket_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='expiry_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Creation date'),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='ticket_state',
            field=models.SmallIntegerField(choices=[(1, 'Tickets on Hold'), (2, 'Unassigned Tickets'), (3, 'Ticket IM Wathing'), (4, 'Overdue Tickets'), (5, 'Open Tickets'), (6, 'Ticket Due Today'), (7, 'In Progress Tickets'), (8, 'Accelated Tickets'), (9, 'Closed Tickets'), (10, 'Cancelled Tickets')], default=1, verbose_name='Publish state'),
        ),
    ]
